'use strict';

/**
 * All HTML-generating functions live here. This is the file to edit when you
 * want to change STRUCTURE (add a meta tag, change the menubar markup, change
 * how a gallery page is laid out). For CONTENT changes (new gallery, new photo,
 * new job on the about page, new nav label) edit data.json instead — you should
 * not need to touch this file for routine updates.
 */

function genComment() {
	return '<!-- AUTO-GENERATED by _build/build.js from _build/data.json + _build/templates.js — do not hand-edit.\n     Change data.json (content) or templates.js (structure), then run `node _build/build.js`. -->';
}

function renderHead({ title, extraCss, description, gaId }) {
	const lines = [
		'\t<meta charset="UTF-8">',
		'\t<meta name="viewport" content="width=device-width, initial-scale=1.0">',
		'\t<meta name="apple-mobile-web-app-capable" content="yes">',
		'\t<meta name="theme-color" content="#222222">',
		'\t<meta name="robots" content="index, follow, noai, noimageai">',
		`\t<title>${title}</title>`
	];
	if (description) {
		lines.push(`\t<meta name="description" content="${description}">`);
	}
	lines.push(
		'\t<link rel="icon" type="image/png" href="img/logo.png" media="(prefers-color-scheme:no-preference)">',
		'\t<link rel="icon" type="image/png" href="img/logo.png" media="(prefers-color-scheme:light)">',
		'\t<link rel="icon" type="image/png" href="img/logo-dark.png" media="(prefers-color-scheme:dark)">',
		'\t<link rel="stylesheet" href="styles/main.css">'
	);
	if (extraCss) {
		lines.push(`\t<link rel="stylesheet" href="styles/${extraCss}">`);
	}
	lines.push(
		'\t<script src="scripts/site.js" defer></script>',
		'\t<!-- Global site tag (gtag.js) - Google Analytics -->',
		`\t<script async src="https://www.googletagmanager.com/gtag/js?id=${gaId}"></script>`,
		'\t<script>',
		'\t\twindow.dataLayer = window.dataLayer || [];',
		'\t\tfunction gtag(){dataLayer.push(arguments);}',
		"\t\tgtag('js', new Date());",
		`\t\tgtag('config', '${gaId}');`,
		'\t</script>'
	);
	return lines.join('\n');
}

function renderMenubar() {
	return [
		'\t<span id="menubar">',
		'\t\t<a href="/work" id="work" class="menubutton">work<hr></a>',
		'\t\t<a href="/" id="title" class="menubutton">omi manav<hr></a>',
		'\t\t<a href="/about" id="about" class="menubutton">about<hr></a>',
		'\t</span>'
	].join('\n');
}

// activeSlug === null means "no single gallery is active" (used on work.html)
function renderSidebar(galleries, activeSlug) {
	const lines = ['\t<span id="art" class="container">'];
	let prevSection = null;
	galleries.forEach((g) => {
		if (prevSection !== null && g.section !== prevSection) {
			lines.push('\t\t<br>');
		}
		const hr = g.slug === activeSlug ? '<hr>' : '';
		lines.push(`\t\t<a href="${g.slug}" class="art button">${g.navLabel}${hr}</a>`);
		prevSection = g.section;
	});
	lines.push('\t</span>');
	return lines.join('\n');
}

function renderGalleryImages(gallery) {
	const lines = [];
	for (let i = 0; i < gallery.count; i++) {
		const n = gallery.start + i;
		const lazy = i === 0 ? '' : ' loading="lazy"';
		lines.push(`\t\t<img src="img/${gallery.folder}/${gallery.prefix}${n}.${gallery.ext}" draggable="false"${lazy}>`);
	}
	return lines.join('\n');
}

function wrapPage(headHtml, bodyHtml) {
	return [
		'<!DOCTYPE html>',
		genComment(),
		'<html lang="en">',
		'<head>',
		headHtml,
		'</head>',
		'<body>',
		bodyHtml,
		'</body>',
		'</html>',
		''
	].join('\n');
}

function renderGalleryPage(gallery, allGalleries, gaId) {
	const head = renderHead({ title: gallery.pageTitle, extraCss: 'gallery.css', gaId });
	const body = [
		renderMenubar(),
		'',
		renderSidebar(allGalleries, gallery.slug),
		'',
		'\t<button id="navToggle" class="nav-toggle" aria-label="Toggle gallery menu" aria-expanded="false" type="button">\u2630</button>',
		'',
		`\t<span id="${gallery.slug}" class="gallery">`,
		renderGalleryImages(gallery),
		'\t</span>'
	].join('\n');
	return wrapPage(head, body);
}

function renderWorkPage(allGalleries, workLinks, gaId) {
	const head = renderHead({ title: 'work', extraCss: 'work.css', gaId });
	const scienceLines = ['\t<span id="science" class="container">'];
	workLinks.forEach((w) => {
		scienceLines.push(`\t\t<a href="${w.href}" class="science button">${w.label}</a>`);
	});
	scienceLines.push('\t</span>');
	const body = [
		renderMenubar(),
		'',
		renderSidebar(allGalleries, null),
		scienceLines.join('\n')
	].join('\n');
	return wrapPage(head, body);
}

function renderAboutPage(about, gaId) {
	const head = renderHead({ title: 'about', extraCss: 'about.css', gaId });
	const workHistoryItems = about.workHistory.map((w) => `\t\t\t<li class="works">${w}</li>`).join('\n');
	// This block was commented out in the original site (a draft of a future
	// work-history update). Preserved verbatim so nothing is lost — uncomment
	// entries in data.json's about.workHistory (or edit here) when ready.
	const draftComment = [
		'\t\t\t<!--',
		'\t\t\t<br>',
		'\t\t\t<li class="works">tech. solutions manager and technician 2024-current</li>',
		'\t\t\t<li class="works">engineer (fujitsu) 2022-2024</li>',
		'\t\t\t<li class="works">engineer (ricoh) 2022-2024</li>',
		'\t\t\t<li class="works">web developer (fanamanga) 2021</li>',
		'\t\t\t<li class="works">tutor (chegg) 2018-2020</li>',
		'\t\t\t<li class="works">private tutoring in photography and computer sciences 2017-2020</li>',
		'\t\t\t<li class="works">development and maintenance of website (bitwiz) 2017-2018</li>',
		'\t\t\t<li class="works">tutor (bitwiz) 2017-2018</li>',
		'\t\t\t-->'
	].join('\n');
	const body = [
		renderMenubar(),
		'',
		'\t<span id="aboutContent">',
		'\t\t<br>',
		'\t\t<span id="summary">',
		`\t\t\t${about.location}`,
		'\t\t\t<br><br>',
		'\t\t\tGet in touch via email;',
		'\t\t\t<br>',
		`\t\t\t<a href="mailto:${about.email}">${about.email}</a>`,
		'\t\t</span>',
		'\t\t<br>',
		'\t\t<ul id="workHistory">',
		'\t\t\t<li class="works"><i>work history</i></li>',
		workHistoryItems,
		'\t\t\t<br>',
		draftComment,
		'\t\t</ul>',
		'\t</span>'
	].join('\n');
	return wrapPage(head, body);
}

function renderIndexPage(gaId) {
	const head = renderHead({
		title: 'omi manav',
		extraCss: null,
		description: 'Photographer and programmer based in New Zealand, working internationally.',
		gaId
	});
	const body = [renderMenubar()].join('\n');
	return wrapPage(head, body);
}

function renderSitemap(baseUrl, galleries, today, preservedEntries) {
	const lines = ['<?xml version="1.0" encoding="UTF-8" ?>', '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'];
	const fixedPages = ['', 'work', 'about'];
	fixedPages.forEach((p) => {
		lines.push(`\t<url><loc>${baseUrl}/${p}</loc><lastmod>${today}</lastmod></url>`);
	});
	galleries.forEach((g) => {
		lines.push(`\t<url><loc>${baseUrl}/${g.slug}</loc><lastmod>${today}</lastmod></url>`);
	});
	lines.push('\t<!-- entries below were present in the previous sitemap but have no corresponding source file in this build; kept as-is, unverified -->');
	preservedEntries.forEach((e) => {
		lines.push(`\t<url><loc>${e.loc}</loc><lastmod>${e.lastmod}</lastmod></url>`);
	});
	lines.push('</urlset>');
	return lines.join('\n') + '\n';
}

module.exports = {
	renderGalleryPage,
	renderWorkPage,
	renderAboutPage,
	renderIndexPage,
	renderSitemap
};
